server:
  port: 8081

s3:
  bucket-name: pavel-shakhlovich-images
  region: eu-central-1
sns:
  topic-arn: arn:aws:sns:eu-central-1:150063193970:task-9-uploads-notification-topic
  region: eu-central-1
sqs:
  queue-url: https://sqs.eu-central-1.amazonaws.com/150063193970/task-9-uploads-notification-queue
  region: eu-central-1
lambda:
  function-name: aws-training-uploads-batch-notifier
  region: eu-central-1
spring:
  datasource:
    url: jdbc:mysql://snssqstask8.cwgkijgrn5hx.eu-central-1.rds.amazonaws.com:3306/snsSqsTask8
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
flyway:
  enabled: true